env:
  base:
  - {image: debian:stretch, pkg-manager: apt}
  - {image: ubuntu:16.04, pkg-manager: apt}
  miniconda:
  - {conda_install: [python=3.5, numpy]}
  - {conda_install: [python=2.7, numpy]}

analysis:
  inputs:
  - [File, -f, list2sort.json]
  script: sorting.py
  command: python

tests:
- {file: array_sorted.npy, name: regr1, script: test_arr_eq.py}
