version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201710-02
    working_directory: /home/circleci/regtests
    steps:
      - checkout:
          path: /home/circleci/regtests
      - run:
          name: install python lib
          command: |
            pip install cwlref-runner
      - run:
          name: Run tests
          no_output_timeout: 60m
          command: |
            python testrunner.py