version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201710-02
    working_directory: /home/circleci/regtests
    steps:
      - checkout:
          path: /home/circleci/regtests
      - run:
          name: Change to Python 3.5.2 and install python dependencies
          command: |
            pyenv global 3.5.2
            pip install cwlref-runner pandas matplotlib mpld3 jinja2 plotly
      - run:
          name: Run tests
          no_output_timeout: 60m
          command: |
            python testrunner.py
      - store_artifacts:
          path: /home/circleci/regtests
