name: test
channels:
- conda-forge
- defaults
dependencies:
- ca-certificates
- certifi=2016.2.28=py27_1
- decorator=4.0.10=py27_0
- funcsigs=1.0.2=py27_0
- future=0.15.2=py27_0
- h5py=2.6.0=np111py27_4
- hdf5=1.8.17=2
- nipype=0.12.0=py27_1
